### ISSUE TITLE
Webpack [ERROR] Error: Cannot find module 'assert/' on sturtup

### ISSUE THREAD

**Issue by oleg-savko** [spring-guides/tut-react-and-spring-data-rest#20]
Cant to start basic modul with command 
./mvnw spring-boot:run
Errors occurs on build process. 
Does somebody know why it can be happened and how to fix this? 

```
[INFO] --- frontend-maven-plugin:0.0.24:npm (npm install) @ react-and-spring-data-rest-basic ---
[INFO] Running 'npm install --color=false' in /Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static
[ERROR] npm WARN package.json spring-data-rest-and-reactjs@0.1.0 No README data
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:webpack (webpack build) @ react-and-spring-data-rest-basic ---
[INFO] Running 'webpack.js --no-color' in /Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'assert/'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.require.resolve (module.js:384:19)
[ERROR]     at Object.<anonymous> (/Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/node_modules/node-libs-browser/index.js:1:93)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/lib/node/NodeSourcePlugin.js:7:23)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at OptionsApply.WebpackOptionsApply.process (/Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/lib/WebpackOptionsApply.js:72:28)
[ERROR]     at webpack (/Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/lib/webpack.js:22:48)
[ERROR]     at processOptions (/Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/bin/webpack.js:152:17)
[ERROR]     at Object.<anonymous> (/Users/aleh/Development/samples/java/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/bin/webpack.js:192:1)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR]     at startup (node.js:119:16)
[ERROR]     at node.js:906:3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.498 s
[INFO] Finished at: 2016-03-31T00:41:45+03:00
[INFO] Final Memory: 18M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.24:webpack (webpack build) on project react-and-spring-data-rest-basic: Failed to run task: 'webpack.js --no-color' failed. (error code 8) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by oleg-savko** [comment]
Fixed by running command `npm i webpack --save-dev`

**Comment by gregturn** [comment]
Odd considering webpack is already an installed module: https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/basic/src/main/resources/static/package.json#L27

I've seen npm's central repo be flippant and sometimes require more than one build job.
