### ISSUE TITLE
Build Failure: Exception in thread "main" java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by MrRoyce** [spring-guides/tut-react-and-spring-data-rest#43]
Hi there, I'm trying to execute the steps as listed in

https://github.com/spring-guides/tut-react-and-spring-data-rest/issues/42

1. Checkout latest copy of tutorial.
2. cd into basic
3. run mvn clean spring-boot:run
4. ...

I get the following error on step 3. 

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/ApplicationEvent
	at com.greglturnquist.payroll.ReactAndSpringDataRestApplication.main(ReactAndSpringDataRestApplication.java:29)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.262 s
[INFO] Finished at: 2017-02-22T10:23:48-05:00
[INFO] Final Memory: 35M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.1.RELEASE:run (default-cli) on project react-and-spring-data-rest-basic: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Here is my 'mvn -v'
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

I'm new to Java, Maven, Spring, etc, but trying to learn.  Any help is appreciated.

Royce

**Comment by gregturn** [comment]
```
ClassNotFoundException: org.springframework.context.ApplicationEvent
```
This implies that it can't even get Spring on the classpath. Which could be a sign of a bad local maven repository. I'd suggest delete ~/.m2 and trying again. That should force maven to pull everything fresh.

I also notice you have maven installed (3.3.9). If you like, you can use the maven wrapper that comes with the project:

```
$ ./mvnw clean spring-boot:run
```

**Comment by MrRoyce** [comment]
Amazing, that worked (deleted ~/.m2, ran ./mvnw...)

Closing.
